name: Lint and Test

on:
    pull_request:
        branches: [main]

jobs:
    lint-and-test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x, 16.x, 22.x]

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: npm install
            - name: Run ESLint
              run: npm run lint
            - name: Run Tests
              run: npm run test
